name: Update Profile Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  profile-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Generate profile cards
        uses: seijikohara/profile-cards-action@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: varad-oss

          cards: |
            overview
            lifetime
            contributions
            composition
            rhythm
            languages

          output-dir: assets/profile
          themes: dark
          font: Roboto
          mono-font: Roboto Mono

          commit: true
          commit-message: "chore: update profile stats [skip ci]"
